KüfürEngelList:
  - amk
  - oç
  - oc
  - o c
  - o ç
  - skm
  - orosbu
  - anneni sikim
  - babanı sikim
  - sikim
  - sikiş
  - porno
  - amınakoyim
  - amına koyim
  - orrosbu evladı
  - orrosbu
  - oççççç
  - oçççç
  - oççç
  - oçç
  - teyzeni sikim
  - amcık
  - am
  - amını
  - amı
  - amın
  - sik
  - siki
  - sikis
  - yavşak
  - mal
  - salak
  - geri zekalı
  - babasız
  - annesiz
  - https
  - youtube
  - orosbu çocuğu
  - piç
  - ananı
  - amk
  - a m k
  - aq
  - aq
  - amq
  - aw
  - amik
  - sikim'
  - sikiyim
  - sikeyim
  - a m ı n o ğ l u
  - amın oğlu
  - gevşek
  - yavsak
  - y a v s a k
  - y a v ş a k
  - sg
  - bok
  - hassiktir
  - hasiktir
  - çiş
  - amık
  - fuck
  - fucuk
  - at büllüğü
  - bülük
  - at bülükü
  - göt
  - g ö t
  - andaval
  - lezbiyen
  - sokma
  - sokuş
  - got
  - AMK
  - OC
  - O C
  - O Ç
  - OÇ